module.exports = {
  ROOT: '../PATH_TO_SOURCE_TO_COMPRESS',
  TEMP: './TEMPORARY_DIRECTORY',
  OUTPUT: '../DIRECTORY_TO_WRITE_COMPRESSED_IMAGES_TO',
  RESIZE_IMAGE_WIDTH: 600,
  JIMP_QUALITY: 70,
  MAX_IMAGE_SIZE: 350000, // IN BYTES 350 KB
  RESIZE_HD_IMAGE_WIDTH: 400,
  MEDIAN_HD_IMAGE_WIDTH: 700,
  MAX_HD_IMAGE_SIZE: 650000
}